# Generated by Django 4.0.6 on 2022-07-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_coffee_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='categories',
            field=models.ManyToManyField(related_name='coffee_list', to='store.category'),
        ),
    ]
