# Generated by Django 4.0.6 on 2022-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_address_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='store.coffee')),
            ],
        ),
    ]
